#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_MIC_GPIO_CLK GPIO_NUM_19
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_39

#define DISPLAY_MOSI_PIN GPIO_NUM_17
#define DISPLAY_CLK_PIN GPIO_NUM_16
#define DISPLAY_DC_PIN GPIO_NUM_14
#define DISPLAY_RST_PIN GPIO_NUM_NC
#define DISPLAY_CS_PIN GPIO_NUM_15

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_23
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_33
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_32

#define BOOT_BUTTON_GPIO GPIO_NUM_34
#define TOUCH_BUTTON_GPIO GPIO_NUM_NC
#define ASR_BUTTON_GPIO GPIO_NUM_NC
#define BUILTIN_LED_GPIO GPIO_NUM_NC

#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_SPI_MODE 0

#endif  // _BOARD_CONFIG_H_
